package entity

const (
	WinType_WIN_TYPE_UNSPECIFIED           int64 = 0
	WIN_TYPE_WIN_CLEAN_DRAGON              int64 = 0x1
	WIN_TYPE_WIN_DRAGON                    int64 = 0x2
	WIN_TYPE_WIN_FIVE_PAIR_THREE_OF_A_KIND int64 = 0x3
	WIN_TYPE_WIN_SIX_AND_A_HALF_PAIRS      int64 = 0x4
	WIN_TYPE_WIN_THREE_STRAIGHT_FLUSH      int64 = 0x5
	WIN_TYPE_WIN_THREE_STRAIGHT            int64 = 0x6
	WIN_TYPE_WIN_THREE_FLUSH               int64 = 0x7
	WIN_TYPE_WIN_FULL_COLORED              int64 = 0x8

	WIN_TYPE_WIN_FRONT_THREE_OF_A_KIND int64 = 0x10
	WIN_TYPE_WIN_MID_FULL_HOUSE        int64 = 0x20
	WIN_TYPE_WIN_BACK_FOUR_OF_A_KIND   int64 = 0x40
	WIN_TYPE_WIN_MID_FOUR_OF_A_KIND    int64 = 0x80
	WIN_TYPE_WIN_BACK_STRAIGHT_FLUSH   int64 = 0x100
	WIN_TYPE_WIN_MID_STRAIGHT_FLUSH    int64 = 0x200
)
